// <auto-generated />
namespace Libanon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LibanonV3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LibanonV3));
        
        string IMigrationMetadata.Id
        {
            get { return "202204260231048_Libanon-V3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
