// <auto-generated />
namespace Libanon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LibanonV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LibanonV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202204270312098_Libanon-V1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
